apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-pod
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
        - name: flask-container
          image: 10.42.0.1:5000/flask-example:99b5191a456d0444908623f1a698a41fa32b1606
          ports:
            - containerPort: 8080
