apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-pod
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
        - name: flask-container
          image: 10.42.0.1:5000/flask-example:6f3cd029cc7f62cb04ebca0c9533d7f822806a07
          ports:
            - containerPort: 8080
