apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-example
spec:
  selector:
    matchLabels:
      app: flask-pod
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
        - name: flask-container
          image: 10.42.0.1:5000/flask-example:0ed8fdc482512c9de7aa1a7f66a68516d0216cc0
          ports:
            - containerPort: 8080
              hostPort: 7080
